#!/usr/bin/env python3
"""Stage manifest generator and checker (ADR 0016, task 05).

Reads the human-authored source ``.fabro/workflows/_io/manifest.json`` plus the
output schemas in ``.fabro/workflows/_io/schemas/`` and produces, for every
workflow, a flat generated manifest embedded in that workflow's ``workflow.toml``
between the fabro-io markers under ``[run.environment.env]``.

The generated manifest is JSON inside a TOML literal string (C2), so it needs no
escaping. ``check`` regenerates it in memory and fails (exit 1, unified diff) if any
``workflow.toml`` differs from the source of truth, and enforces the offline checks
C2 lists. Python 3.11+ standard library only; runs on the Mac and on the host, never
in a sandbox.

Usage:
    python3.11 ops/fabro-io-manifest.py generate   # rewrite the four workflow.toml files
    python3.11 ops/fabro-io-manifest.py check      # no writes; exit 1 on any drift/Gate
"""

from __future__ import annotations

import argparse
import difflib
import fnmatch
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
IO = REPO / ".fabro" / "workflows" / "_io"
WORKFLOWS = REPO / ".fabro" / "workflows"
SCHEMAS = IO / "schemas"
SOURCE = IO / "manifest.json"

# Deterministic emit order.
WF_ORDER = ["backlog", "pr-review", "arch-review", "issue-triage"]

# The exact markers C2 specifies.
BEGIN = "# BEGIN fabro-io manifest (generated by ops/fabro-io-manifest.py; do not edit)"
END = "# END fabro-io manifest"

# The agent guide block (docs/coder-tweaks C1), next to the manifest block.
GUIDE = IO / "agent-guide.md"
GUIDE_MAX_BYTES = 3000
GUIDE_BEGIN = "# BEGIN fabro agent guide (generated by ops/fabro-io-manifest.py from _io/agent-guide.md; do not edit)"
GUIDE_END = "# END fabro agent guide"

TMP_RE = re.compile(r"/tmp/fabro/[^\s`'\")\]>,}\]]+")

# --------------------------------------------------------------------------- #
# .fabro node parsing                                                          #
# --------------------------------------------------------------------------- #

def read_file(path: Path) -> str:
    return path.read_text()

def find_imports(workflow: str) -> dict[str, str]:
    """{import_node_id: phase} from the workflow's .fabro import edges."""
    text = read_file(WORKFLOWS / workflow / "workflow.fabro")
    out: dict[str, str] = {}
    for m in re.finditer(
        r'^\s*(\w+)\s*\[\s*[^\]]*?\bimport="\.\./_shared/([\w-]+)/[\w-]+\.fabro"',
        text,
        re.M,
    ):
        out[m.group(1)] = m.group(2)
    return out

def nodes_in(text: str) -> dict[str, dict[str, str]]:
    """node_id -> attribute dict for single-line nodes in a .fabro file."""
    out: dict[str, dict[str, str]] = {}
    for m in re.finditer(r"^\s*(\w+)\s*\[(.*?)\]", text, re.M | re.S):
        out[m.group(1)] = dict(
            (p.group(1), p.group(2)) for p in re.finditer(
                r'(\w+)\s*=\s*("(?:[^"\\]|\\.)*"?|@[^\s,"\]]*|[^\s,"\]]*)', m.group(2)
            )
        )
    return out

def is_agent_node(attrs: dict[str, str]) -> bool:
    if "prompt" not in attrs:
        return False
    shape = attrs.get("shape", "").strip('"')
    return shape in ("", "box")

# --------------------------------------------------------------------------- #
# source / schema loading                                                      #
# --------------------------------------------------------------------------- #

def load_source() -> dict:
    return json.loads(SOURCE.read_text())

def load_schemas() -> dict[str, dict]:
    out: dict[str, dict] = {}
    for f in sorted(SCHEMAS.glob("*.schema.json")):
        out[f.name.removesuffix(".schema.json")] = json.loads(f.read_text())
    return out

def materialize(spec: dict, schemas: dict[str, dict]) -> dict:
    """Flat generated stage: inputs/output/sealed/git only (server adds _io)."""
    stage: dict[str, object] = {}
    stage["inputs"] = [
        {k: v for k, v in {
            "name": i["name"], "path": i["path"],
            "required": bool(i.get("required", False)),
            "about": i.get("about", ""),
            **({"absent": i["absent"]} if i.get("absent") else {}),
        }.items() if v != "" or k == "required"}
        for i in spec.get("inputs", [])
    ]
    if spec.get("output"):
        stage["output"] = {
            "path": spec["output"]["path"],
            "schema": schemas[spec["output"]["schema"]],
        }
    if spec.get("sealed"):
        stage["sealed"] = spec["sealed"]
    if spec.get("git"):
        stage["git"] = spec["git"]
    return stage

def generated_for(workflow: str, src: dict, schemas: dict[str, dict]) -> dict:
    stages: dict[str, dict] = {}
    wf = src["workflows"][workflow]
    for sid, spec in wf.get("stages", {}).items():
        if spec.get("live"):
            stages[sid] = materialize(spec, schemas)
    for node, phase in find_imports(workflow).items():
        for sid, spec in src["phases"].get(phase, {}).items():
            if spec.get("live"):
                stages[f"{node}.{sid}"] = materialize(spec, schemas)
    return {"version": src["version"], "min_binary": src["min_binary"], "stages": stages}

def compact_json(obj: dict) -> str:
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=True)

# --------------------------------------------------------------------------- #
# workflow.toml mutation                                                       #
# --------------------------------------------------------------------------- #

def env_bounds(lines: list[str]) -> tuple[int | None, int | None]:
    start = next((i for i, ln in enumerate(lines)
                  if re.match(r"^\[run\.environment\.env\]\s*$", ln)), None)
    if start is None:
        return None, None
    end = len(lines)
    for i in range(start + 1, len(lines)):
        if re.match(r"^\s*\[", lines[i]):
            end = i
            break
    return start, end

def inject_manifest(text: str, workflow: str, generated: dict) -> str:
    body = compact_json(generated)
    if "'''" in body:
        raise RuntimeError(f"{workflow}: generated manifest contains ''' (C2)")
    block = (
        f"{BEGIN}\n"
        f"FABRO_IO_MANIFEST = '''{body}'''\n"
        f"{END}\n"
    )
    lines = text.splitlines(keepends=True)
    start, end = env_bounds(lines)

    def replace(lo: int, hi: int) -> str:
        return "".join(lines[:lo]) + block + "".join(lines[hi:])

    if start is None:
        insert_at = len(lines)
        for i, ln in enumerate(lines):
            if ln.startswith("[[run.hooks]]"):
                insert_at = i
                break
        return "".join(lines[:insert_at]) + "[run.environment.env]\n" + block + "".join(lines[insert_at:])

    b = e = None
    for i in range(start, end):
        if lines[i].startswith(BEGIN):
            b = i
        if lines[i].startswith(END):
            e = i
    if b is not None and e is not None and b < e:
        return replace(b, e + 1)
    return replace(start + 1, start + 1)

def guide_text() -> str:
    return GUIDE.read_text()

def guide_problems(text: str) -> list[str]:
    out = []
    if len(text.encode()) > GUIDE_MAX_BYTES:
        out.append(f"guide: _io/agent-guide.md is {len(text.encode())} bytes, over {GUIDE_MAX_BYTES}")
    if "'''" in text:
        out.append("guide: _io/agent-guide.md contains ''' (it sits in a TOML literal string)")
    if not text.strip():
        out.append("guide: _io/agent-guide.md is empty")
    return out

def inject_guide(text: str, guide: str) -> str:
    """Write the FABRO_AGENT_GUIDE block just after the manifest block (C1)."""
    if "'''" in guide:
        raise RuntimeError("agent guide contains ''' (C1)")
    block = f"{GUIDE_BEGIN}\nFABRO_AGENT_GUIDE = '''{guide}'''\n{GUIDE_END}\n"
    lines = text.splitlines(keepends=True)
    b = next((i for i, ln in enumerate(lines) if ln.startswith(GUIDE_BEGIN)), None)
    e = next((i for i, ln in enumerate(lines) if ln.startswith(GUIDE_END)), None)
    if b is not None and e is not None and b < e:
        return "".join(lines[:b]) + block + "".join(lines[e + 1:])
    m_end = next((i for i, ln in enumerate(lines) if ln.startswith(END)), None)
    if m_end is None:
        raise RuntimeError("no manifest block to put the agent guide after")
    return "".join(lines[:m_end + 1]) + block + "".join(lines[m_end + 1:])

# --------------------------------------------------------------------------- #
# checks                                                                       #
# --------------------------------------------------------------------------- #

def attrs_of(sid: str, workflow: str, imports: dict[str, str]) -> dict[str, str]:
    """Attributes of a node in its defining graph (own workflow or an imported phase)."""
    own = nodes_in(read_file(WORKFLOWS / workflow / "workflow.fabro"))
    if sid in own:
        return own[sid]
    for node, phase in imports.items():
        if sid.startswith(node + "."):
            base = sid[len(node) + 1:]
            ph = nodes_in(read_file(WORKFLOWS / "_shared" / phase / f"{phase}.fabro"))
            if base in ph:
                return ph[base]
    return {}

def spec_prompt_path(spec: dict) -> Path:
    p = spec["prompt"]
    return Path(p) if p.startswith("/") else (REPO / p)

def tmp_paths(text: str) -> set[str]:
    return set(TMP_RE.findall(text))

def do_not_read_lines(text: str) -> set[str]:
    """Lines in a prompt that forbid reading paths (the 'sealed' instruction)."""
    out: set[str] = set()
    for ln in text.splitlines():
        low = ln.lower()
        if re.search(r"(do not read|must not read|do not open|must not open|not open|never read)", low):
            out.add(ln)
    return out

def check() -> int:
    src = load_source()
    schemas = load_schemas()
    fails: list[str] = []

    # rule 5: no ''' in any generated manifest
    for wf in WF_ORDER:
        body = compact_json(generated_for(wf, src, schemas))
        if "'''" in body:
            fails.append(f"rule5: {wf} generated manifest contains '''")

    wf_specs: dict[str, dict[str, dict]] = {}
    for wf in WF_ORDER:
        imports = find_imports(wf)
        specs: dict[str, dict] = {}
        for sid, spec in src["workflows"][wf].get("stages", {}).items():
            specs[sid] = spec
        for node, phase in imports.items():
            for sid, spec in src["phases"].get(phase, {}).items():
                specs[f"{node}.{sid}"] = spec
        wf_specs[wf] = specs

    for wf, specs in wf_specs.items():
        imports = find_imports(wf)
        for sid, spec in specs.items():
            # rule 1: agent node
            if not is_agent_node(attrs_of(sid, wf, imports)):
                fails.append(f"rule1: {wf} {sid}: not an agent node")
            # rules 3/4: prompt path discipline
            prompt_path = spec_prompt_path(spec)
            if not prompt_path.exists():
                fails.append(f"{wf} {sid}: prompt missing: {prompt_path}")
                continue
            ptext = prompt_path.read_text()
            names = tmp_paths(ptext)
            allowed = {i["path"] for i in spec.get("inputs", []) if i["path"].startswith("/tmp/fabro")}
            if spec.get("output"):
                allowed.add(spec["output"]["path"])
            allowed.update(spec.get("also", []))
            if spec.get("live"):
                forbid = do_not_read_lines(ptext)
                for name in names:
                    if any(ln in forbid and (name in ln or name.rstrip("/") in ln) for ln in ptext.splitlines() if ln in forbid):
                        continue
                    for pat in spec.get("sealed", []):
                        if matches(name, pat):
                            fails.append(f"rule3: {wf} {sid}: live prompt names sealed path {name!r} ({pat})")
                            break
            else:
                for name in sorted(names):
                    if name in allowed or any(name.startswith(a) for a in allowed if a.endswith("/")):
                        continue
                    if any(ln in do_not_read_lines(ptext) and name in ln for ln in ptext.splitlines()):
                        continue
                    fails.append(f"rule4: {wf} {sid}: non-live prompt names undeclared path {name!r}")

    # rule 5b: workflow.toml manifests must not contain '''
    for wf in WF_ORDER:
        text = (WORKFLOWS / wf / "workflow.toml").read_text()
        for m in re.finditer(r"FABRO_IO_MANIFEST = '''(.*?)'''", text, re.S):
            if "'''" in m.group(1):
                fails.append(f"rule5: {wf} workflow.toml manifest contains '''")

    fails.extend(guide_problems(guide_text()))

    # drift
    for wf in WF_ORDER:
        p = WORKFLOWS / wf / "workflow.toml"
        text = p.read_text()
        expected = inject_guide(inject_manifest(text, wf, generated_for(wf, src, schemas)), guide_text())
        if expected != text:
            diff = difflib.unified_diff(
                text.splitlines(), expected.splitlines(),
                fromfile=f"{wf}/workflow.toml (committed)", tofile=f"{wf}/workflow.toml (generated)",
            )
            fails.append(f"drift: {wf}/workflow.toml differs from generated:\n" + "\n".join(diff))

    if fails:
        print("ops/fabro-io-manifest.py check FAILED:")
        for f in fails:
            print("  " + f.replace("\n", "\n  "))
        return 1
    print("ops/fabro-io-manifest.py check OK")
    return 0

def matches(name: str, pattern: str) -> bool:
    pat = pattern.strip()
    if not pat:
        return False
    if "*" in pat:
        return fnmatch.fnmatch(name, pat) or fnmatch.fnmatch(name.rstrip("/"), pat)
    return pat in name or name.startswith(pat)

# --------------------------------------------------------------------------- #
# generate                                                                     #
# --------------------------------------------------------------------------- #

def generate() -> None:
    src = load_source()
    schemas = load_schemas()
    for wf in WF_ORDER:
        p = WORKFLOWS / wf / "workflow.toml"
        gen = generated_for(wf, src, schemas)
        p.write_text(inject_guide(inject_manifest(p.read_text(), wf, gen), guide_text()))
        print(f"{wf}: {len(gen['stages'])} live stage(s)")

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["generate", "check"])
    args = ap.parse_args()
    if args.cmd == "generate":
        problems = guide_problems(guide_text())
        if problems:
            print("\n".join(problems), file=sys.stderr)
            return 1
        generate()
        return 0
    return check()


if __name__ == "__main__":
    sys.exit(main())
